# Generated by Django 5.0.3 on 2024-03-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='existence',
            field=models.BooleanField(default=False),
        ),
    ]
